// components/agents/AgentWorkspace.tsx
'use client';

import React, { useMemo } from 'react';
import { AgentId, AGENT_META, type AgentVoteRecord, type MemoryEntry, type AgentMessageRecord } from '@/types';

interface AgentWorkspaceProps {
  agentId: AgentId | null;
  vote: AgentVoteRecord | null;
  shortTermMemories: MemoryEntry[];
  debateMessages: AgentMessageRecord[];
  agentStatus: { status: string; message?: string; confidence?: number; urgency?: number } | null;
}

export const AgentWorkspace: React.FC<AgentWorkspaceProps> = ({
  agentId,
  vote,
  shortTermMemories,
  debateMessages,
  agentStatus,
}) => {
  if (!agentId) {
    return (
      <div className="eoc-panel" style={{ flex: 1 }}>
        <div className="eoc-panel-header">
          <span>Agent Workspace</span>
        </div>
        <div className="eoc-panel-content" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%', color: 'var(--text-muted)' }}>
          <div style={{ textAlign: 'center', fontFamily: 'var(--font-mono)', fontSize: '11px' }}>
            [!] SELECT AN AGENT FROM ROSTER TO MOUNT WORKSPACE
          </div>
        </div>
      </div>
    );
  }

  const formatTime = (timeInput: any) => {
    try {
      const d = new Date(timeInput);
      if (isNaN(d.getTime())) return '--:--:--';
      return d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' });
    } catch {
      return '--:--:--';
    }
  };

  const meta = AGENT_META[agentId];

  // Specific current tasks for immersive EOC context
  const agentTasks: Record<AgentId, string> = {
    SIGMA: 'Analyzing incident feeds, classifying disaster type, and calculating impact severity.',
    AXIOM: 'Evaluating logical consistency, detecting duplications, and verifying citizen report facts.',
    HERALD: 'Scraping external weather channels and scanning routes for hazard blockages.',
    AEGIS: 'Checking inventory pools, computing resource constraints, and preparing unit dispatches.',
    ATLAS: 'Designing evacuation parameters, analyzing safe zones, and plotting optimal transit paths.',
    ARCHIVE: 'Cross-referencing historical disaster databases for strategies and lessons learned.',
    NEXUS: 'Aggregating specialist proposals, resolving route conflicts, and synthesizing final actions.',
  };

  const getVoteColor = (v: string) => {
    switch (v) {
      case 'AGREE':
      case 'YES':
      case 'APPROVE':
        return 'var(--status-live)';
      case 'PARTIAL':
        return 'var(--status-warn)';
      case 'DISAGREE':
      case 'NO':
        return 'var(--status-crit)';
      default:
        return 'var(--text-secondary)';
    }
  };

  const getAgentColor = (id: AgentId) => {
    switch (id) {
      case AgentId.SIGMA: return 'var(--sigma)';
      case AgentId.AXIOM: return 'var(--axiom)';
      case AgentId.HERALD: return 'var(--herald)';
      case AgentId.AEGIS: return 'var(--aegis)';
      case AgentId.ATLAS: return 'var(--atlas)';
      case AgentId.ARCHIVE: return 'var(--archive)';
      case AgentId.NEXUS: return 'var(--nexus)';
      default: return 'var(--text-secondary)';
    }
  };

  // Filter messages generated by this agent in the current run
  const agentHistory = useMemo(() => {
    return debateMessages.filter(msg => msg.fromAgent === agentId);
  }, [debateMessages, agentId]);

  // Derived latency (simulated but static based on agent complexity)
  const agentLatency = useMemo(() => {
    const base = {
      SIGMA: '1.24s',
      AXIOM: '1.45s',
      HERALD: '1.08s',
      AEGIS: '1.62s',
      ATLAS: '1.54s',
      ARCHIVE: '1.18s',
      NEXUS: '2.12s',
    }[agentId];
    return base ?? '1.50s';
  }, [agentId]);

  return (
    <div className="eoc-panel" style={{ flex: 1.8, display: 'flex', flexDirection: 'column', height: '100%', overflow: 'hidden' }}>
      <div className="eoc-panel-header" style={{ flexShrink: 0 }}>
        <span>Workspace — {meta.name}</span>
        <span className="font-mono text-cyan" style={{ fontSize: '9px' }}>
          LATENCY: {agentLatency}
        </span>
      </div>

      <div className="eoc-panel-content" style={{ display: 'flex', flexDirection: 'column', gap: '10px', overflowY: 'auto' }}>
        
        {/* Profile Card & Avatar HUD */}
        <div
          style={{
            backgroundColor: 'var(--bg-panel-alt)',
            border: '1px solid var(--border)',
            borderRadius: '4px',
            padding: '10px 12px',
            display: 'flex',
            alignItems: 'center',
            gap: '12px',
          }}
        >
          {/* Avatar Graphic */}
          <div
            style={{
              width: '42px',
              height: '42px',
              borderRadius: '8px',
              backgroundColor: 'rgba(0,0,0,0.3)',
              border: `1px solid ${getAgentColor(agentId)}`,
              boxShadow: `0 0 10px ${getAgentColor(agentId)}20`,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              fontSize: '20px',
              color: getAgentColor(agentId),
              userSelect: 'none',
              flexShrink: 0,
            }}
          >
            {meta.glyph}
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '2px', flex: 1 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <span className="font-mono" style={{ fontSize: '12px', fontWeight: 700, color: 'var(--text-primary)' }}>
                {meta.name} SPECIALIST
              </span>
              <span className="font-mono" style={{ fontSize: '8px', color: 'var(--text-secondary)' }}>
                {meta.role.toUpperCase()}
              </span>
            </div>
            <p style={{ fontSize: '10px', color: 'var(--text-secondary)', lineHeight: '1.4', margin: 0 }}>
              Persona: <span style={{ fontStyle: 'italic', color: 'var(--text-primary)' }}>{meta.personality}</span>
            </p>
          </div>
        </div>

        {/* Current Task & Running State */}
        <div style={{ backgroundColor: 'rgba(0,0,0,0.2)', border: '1px solid var(--border)', borderRadius: '4px', padding: '8px 10px' }}>
          <div style={{ fontSize: '8px', textTransform: 'uppercase', color: 'var(--text-secondary)', fontWeight: 700, letterSpacing: '0.05em', marginBottom: '2px' }}>
            Active Task Assignment
          </div>
          <p style={{ fontSize: '11px', color: 'var(--text-primary)', margin: 0, lineHeight: 1.4 }}>
            {agentTasks[agentId]}
          </p>
          {agentStatus && agentStatus.message && (
            <div style={{ marginTop: '6px', fontSize: '9px', color: 'var(--status-warn)', fontFamily: 'var(--font-mono)' }}>
              &gt; STATUS: {agentStatus.status} - {agentStatus.message}
            </div>
          )}
        </div>

        {/* Performance & Decision Grid */}
        {vote ? (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '6px' }}>
              <div style={{ backgroundColor: 'var(--bg-panel-alt)', padding: '6px 8px', borderRadius: '3px', border: '1px solid var(--border)', display: 'flex', flexDirection: 'column' }}>
                <span style={{ fontSize: '7px', color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: '0.02em' }}>DECISION</span>
                <span className="font-mono" style={{ fontSize: '11px', fontWeight: 700, color: getVoteColor(vote.vote), marginTop: '2px' }}>
                  {vote.vote}
                </span>
              </div>
              <div style={{ backgroundColor: 'var(--bg-panel-alt)', padding: '6px 8px', borderRadius: '3px', border: '1px solid var(--border)', display: 'flex', flexDirection: 'column' }}>
                <span style={{ fontSize: '7px', color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: '0.02em' }}>CONFIDENCE</span>
                <span className="font-mono text-cyan" style={{ fontSize: '11px', fontWeight: 700, marginTop: '2px' }}>
                  {Math.round((agentStatus?.confidence ?? vote.confidence) * 100)}%
                </span>
              </div>
              <div style={{ backgroundColor: 'var(--bg-panel-alt)', padding: '6px 8px', borderRadius: '3px', border: '1px solid var(--border)', display: 'flex', flexDirection: 'column' }}>
                <span style={{ fontSize: '7px', color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: '0.02em' }}>URGENCY</span>
                <span className="font-mono" style={{ fontSize: '11px', fontWeight: 700, color: 'var(--status-warn)', marginTop: '2px' }}>
                  {Math.round((agentStatus?.urgency ?? vote.urgency) * 100)}%
                </span>
              </div>
            </div>

            {/* Current Reasoning Section */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
              <span style={{ fontSize: '8px', textTransform: 'uppercase', color: 'var(--text-secondary)', fontWeight: 700, letterSpacing: '0.05em' }}>
                Reasoning Path
              </span>
              <p style={{ fontSize: '11px', color: 'var(--text-primary)', lineHeight: '1.4', backgroundColor: 'var(--bg-panel-alt)', border: '1px solid var(--border)', borderRadius: '4px', padding: '8px', margin: 0, fontStyle: 'italic' }}>
                {vote.reasoning}
              </p>
            </div>

            {/* Recommendation Proposal */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
              <span style={{ fontSize: '8px', textTransform: 'uppercase', color: 'var(--text-secondary)', fontWeight: 700, letterSpacing: '0.05em' }}>
                Action Recommendation
              </span>
              <p style={{ fontSize: '11px', color: 'var(--text-primary)', lineHeight: '1.4', backgroundColor: 'var(--bg-panel-alt)', border: '1px solid var(--border)', borderRadius: '4px', padding: '8px', margin: 0 }}>
                {vote.recommendation}
              </p>
            </div>

            {/* Memory traces */}
            {(vote.memoryUsed || vote.memoryInfluence) && (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
                <span style={{ fontSize: '8px', textTransform: 'uppercase', color: 'var(--text-secondary)', fontWeight: 700, letterSpacing: '0.05em' }}>
                  Memory Influence Trace
                </span>
                <div style={{ backgroundColor: 'rgba(0, 212, 255, 0.03)', border: '1px dashed var(--accent-dim)', borderRadius: '4px', padding: '8px' }}>
                  <div style={{ fontSize: '9px', fontWeight: 700, color: 'var(--accent)' }}>
                    Matched Precedents Database Access
                  </div>
                  <p style={{ fontSize: '10px', color: 'var(--text-primary)', marginTop: '4px', margin: 0, lineHeight: 1.4 }}>
                    {vote.memoryInfluence || 'Referenced historical incident metrics in Neon storage pool.'}
                  </p>
                </div>
              </div>
            )}

            {/* Risk Assessments */}
            {vote.risks && vote.risks.length > 0 && (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
                <span style={{ fontSize: '8px', textTransform: 'uppercase', color: 'var(--text-secondary)', fontWeight: 700, letterSpacing: '0.05em' }}>
                  Risk Assessment Matrix
                </span>
                <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
                  {vote.risks.map((risk, index) => (
                    <div
                      key={index}
                      style={{
                        fontSize: '10px',
                        color: 'var(--status-crit)',
                        backgroundColor: 'rgba(252, 129, 129, 0.06)',
                        border: '1px solid rgba(252, 129, 129, 0.15)',
                        borderRadius: '3px',
                        padding: '4px 8px',
                        display: 'flex',
                        gap: '6px',
                        alignItems: 'center',
                      }}
                    >
                      <span style={{ fontSize: '12px' }}>⚠</span>
                      <span>{risk}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        ) : (
          <div
            style={{
              padding: '16px',
              textAlign: 'center',
              color: 'var(--text-muted)',
              fontSize: '11px',
              border: '1px dashed var(--border)',
              borderRadius: '4px',
            }}
          >
            No formal votes logged yet in active run.
          </div>
        )}

        {/* History / Evidence log from current debate */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '6px', borderTop: '1px solid var(--border)', paddingTop: '10px' }}>
          <span style={{ fontSize: '9px', textTransform: 'uppercase', color: 'var(--text-secondary)', fontWeight: 700, letterSpacing: '0.05em' }}>
            Debate Action Log ({agentHistory.length})
          </span>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
            {agentHistory.length === 0 ? (
              <div style={{ fontSize: '10px', color: 'var(--text-muted)', fontStyle: 'italic', padding: '4px 0' }}>
                No debate transmissions registered yet.
              </div>
            ) : (
              agentHistory.map(msg => (
                <div
                  key={msg.id}
                  className="animate-slide-in"
                  style={{
                    backgroundColor: 'var(--bg-panel-alt)',
                    border: '1px solid var(--border)',
                    borderRadius: '4px',
                    padding: '8px',
                  }}
                >
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '4px' }}>
                    <span
                      className="font-mono text-cyan"
                      style={{
                        fontSize: '8px',
                        fontWeight: 700,
                        backgroundColor: 'rgba(0,212,255,0.06)',
                        padding: '1px 4px',
                        borderRadius: '2px',
                      }}
                    >
                      {msg.messageType}
                    </span>
                    <span className="font-mono" style={{ fontSize: '7px', color: 'var(--text-muted)' }}>
                      ROUND {msg.round} · {formatTime(msg.timestamp)}
                    </span>
                  </div>
                  <p style={{ fontSize: '10px', color: 'var(--text-primary)', margin: 0, lineHeight: 1.4 }}>
                    {msg.content}
                  </p>
                  {msg.reasoning && (
                    <div style={{ marginTop: '4px', borderTop: '1px solid rgba(255,255,255,0.03)', paddingTop: '4px', fontSize: '9px', color: 'var(--text-secondary)', fontStyle: 'italic' }}>
                      Reasoning: {msg.reasoning}
                    </div>
                  )}
                </div>
              ))
            )}
          </div>
        </div>

        {/* Private short term memory recall */}
        {shortTermMemories.length > 0 && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '6px', borderTop: '1px solid var(--border)', paddingTop: '10px' }}>
            <span style={{ fontSize: '9px', textTransform: 'uppercase', color: 'var(--text-secondary)', fontWeight: 700, letterSpacing: '0.05em' }}>
              Short-Term Memory Recall (Session)
            </span>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
              {shortTermMemories.map((entry, index) => (
                <div
                  key={index}
                  style={{
                    backgroundColor: 'var(--bg-panel-alt)',
                    border: '1px solid var(--border)',
                    borderRadius: '4px',
                    padding: '8px',
                  }}
                >
                  <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '7px', color: 'var(--text-muted)', marginBottom: '2px' }}>
                    <span>INCIDENT ID: {entry.incidentId.slice(-8)}</span>
                    <span className="font-mono">CONF: {Math.round(entry.confidence * 100)}%</span>
                  </div>
                  <p style={{ fontSize: '10px', color: 'var(--text-primary)', margin: 0, lineHeight: 1.4 }}>
                    {entry.observation}
                  </p>
                  {entry.outcome && (
                    <div style={{ fontSize: '9px', color: 'var(--status-live)', marginTop: '4px', fontWeight: 600 }}>
                      Outcome: {entry.outcome}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default AgentWorkspace;
